In [8]:
import numpy as np
import pandas as pd
from tqdm import tqdm
import json
import cv2
import os
import re
import pickle
import math
from pathlib import *
import multiprocessing
import random
import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn
from collections import *
from itertools import *
from functools import *
from sklearn.metrics import *
from scipy.stats import *
import pandas as pd
import seaborn as sns
import hashlib
from PIL import Image
from datastatics.py import *
import da

ModuleNotFoundError: No module named 'datastatics'

In [6]:
map_matrix='''[ [0  0  0  0  0  0  0  0  0  0]
                [0  0  0  46 44 43 42 0  0  0]
                [0  0  46 45 44 43 41 43 0  0]
                [0  45 46 45 45 45 42 42 41 0]
                [46 46 47 46 50 50 50 0  41 0]
                [9  9  9  6  8  6  7  0  16 0]
                [0  10 8  7  6  8  9  13 17 0]
                [0  0  8  8  10 10 12 15 0  0]
                [0  0  0  9  10 11 14 0  0  0]
                [0  0  0  0  0  0  0  0  0  0]]'''


def str_to_np_array(row, dtype=np.float):
    row = row.replace('[', '').replace(']', '')
    row = row.split(' ')
    row = filter(lambda x: x != '', row)
    row = map(lambda x: dtype(x), row)
    row = np.array(list(row))
    return row

def str_to_np_mat(s, dtype=np.float):
    s = s[1:-1]
    rows = s.split('\n')
    for index, row in enumerate(rows):
        rows[index] = str_to_np_array(row, dtype)
    rows = np.stack(rows, axis=0)
    return rows

import itertools
def calculate_position(arr):
	#拼接数组函数
    array_num = list(itertools.chain.from_iterable(arr))
    array_num = np.array(array_num)
    key = np.unique(array_num)
    result = {}
    for k in key:
        index=np.argwhere(arr == k)#返回所有符合条件的索引值，更多的方法和类参数需要看
        v=[tuple(index[i]) for i in range(0,len(index))]
        result[k] = v
    result = {key:val for key, val in result.items() if  len(val)<9}  
    return result

num_mat=str_to_np_mat(map_matrix)
countNums=calculate_position(num_mat)

In [ ]:
data=pd.read_csv('data.csv')#
data['np_mat_num']=data['num'].apply(str_to_np_mat)
data['np_mat_num']=data['np_mat_num'].mask(data['eye']=='OD',data['np_mat_num'].apply(lambda x:np.flip(x,axis=1)))#all_num已经翻转过，所以数据是正常的
all_num=data['np_mat_num']
def split_np_matrix(all_num,data:pd.DataFrame):
    res=np.zeros((1,100))
    for num in all_num:
        res=np.concatenate((res,np.expand_dims(num.flatten(),0)),axis=0)
    res=res[1:]
    for i in range(0,res.shape[1]):
        
        data[f'({i//10},{(i-1)%10})']=res[:,i]
    return data

    
new_data=split_np_matrix(all_num,data)
new_data.to_csv('new_data.csv')#这里用excel preview看数据就出现了19.0，但实际上通过调用columns属性就可以得出其实数据属性列是正常的
bupt=pd.read_csv('new_data.csv')
new_data.to_csv('new_data.csv')